### ISSUE TITLE
CardanoAfterDark meeting - 2021-12-01, 16:00 UTC

### ISSUE THREAD

**Issue by Seomon4u** [Cardano-After-Dark/co-ordination#1]
CardanoAfterDark - 2021-12-01, 16:00 UTC

### Moderator
- [x] Seomon @Seomon4u 

### Attendees
Checked Names confirmed as Attendees.

- [x] Steve @theRealArchangelBob
- [x] Cagkan
- [x] Cem @ckaraca 
- [x] Patrik @psuzzi 
- [x] David @davidbaxter30 
- [x] Shannon
- [x] Nori @xeeban 

### Documentation

- [x] Seomon @Seomon4u 

## Agenda Items

- [x] Meetings
- [x] website shannon
- [x] architecture

## Action

- [x] connect with adriano the human @Steve

## Notes
[Patriks notes](https://docs.google.com/document/d/14_JWPSj0kNn8ogIPxGrhkqF-MXJoC-cc7hzowA53sg0/edit#heading=h.w7eqn3putnkd)
### meetings

biweekly - Monday 17:00 UTC
next meeting -15.12.2021
What is the meeting for:

### architecture

https://docs.google.com/document/d/14_JWPSj0kNn8ogIPxGrhkqF-MXJoC-cc7hzowA53sg0/edit?usp=sharing

Nori:Wallet can't be integrated in Cardano yet, we should find someone.
steve: adriano the human is working on the gamechanger wallet.

Nori presentation of Metamask

**Comment by xeeban** [comment]
+1

**Comment by Seomon4u** [comment]
Wohoo

**Comment by davidbaxter30** [comment]
Hey there!
